import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const historicalPersons = [
  {
    name: 'Наполеон Бонапарт',
    nameEn: 'Napoleon Bonaparte',
    description: 'Французский император и военный полководец, один из самых известных правителей в истории',
    era: '19th Century',
    category: 'Politician',
    country: 'France',
    birthYear: 1769,
    deathYear: 1821,
  },
  {
    name: 'Леонардо да Винчи',
    nameEn: 'Leonardo da Vinci',
    description: 'Итальянский художник, изобретатель, ученый эпохи Возрождения',
    era: 'Renaissance',
    category: 'Artist',
    country: 'Italy',
    birthYear: 1452,
    deathYear: 1519,
  },
  {
    name: 'Юлий Цезарь',
    nameEn: 'Julius Caesar',
    description: 'Римский полководец и политик, диктатор Римской республики',
    era: 'Ancient',
    category: 'Politician',
    country: 'Rome',
    birthYear: 100,
    deathYear: 44,
  },
  {
    name: 'Альберт Эйнштейн',
    nameEn: 'Albert Einstein',
    description: 'Немецкий физик-теоретик, создатель теории относительности',
    era: '20th Century',
    category: 'Scientist',
    country: 'Germany',
    birthYear: 1879,
    deathYear: 1955,
  },
  {
    name: 'Клеопатра',
    nameEn: 'Cleopatra',
    description: 'Последняя царица эллинистического Египта из македонской династии Птолемеев',
    era: 'Ancient',
    category: 'Politician',
    country: 'Egypt',
    birthYear: 69,
    deathYear: 30,
  },
  {
    name: 'Александр Македонский',
    nameEn: 'Alexander the Great',
    description: 'Македонский царь и полководец, создатель одной из крупнейших империй древности',
    era: 'Ancient',
    category: 'Politician',
    country: 'Macedonia',
    birthYear: 356,
    deathYear: 323,
  },
  {
    name: 'Вольфганг Амадей Моцарт',
    nameEn: 'Wolfgang Amadeus Mozart',
    description: 'Австрийский композитор и музыкант, один из величайших композиторов в истории',
    era: '18th Century',
    category: 'Artist',
    country: 'Austria',
    birthYear: 1756,
    deathYear: 1791,
  },
  {
    name: 'Жанна д\'Арк',
    nameEn: 'Joan of Arc',
    description: 'Французская героиня, национальная святая, участница Столетней войны',
    era: 'Medieval',
    category: 'Military',
    country: 'France',
    birthYear: 1412,
    deathYear: 1431,
  },
  {
    name: 'Уильям Шекспир',
    nameEn: 'William Shakespeare',
    description: 'Английский поэт и драматург, величайший писатель английской литературы',
    era: 'Renaissance',
    category: 'Artist',
    country: 'England',
    birthYear: 1564,
    deathYear: 1616,
  },
  {
    name: 'Исаак Ньютон',
    nameEn: 'Isaac Newton',
    description: 'Английский физик, математик и астроном, один из основателей классической физики',
    era: '17th Century',
    category: 'Scientist',
    country: 'England',
    birthYear: 1643,
    deathYear: 1727,
  },
  {
    name: 'Микеланджело',
    nameEn: 'Michelangelo',
    description: 'Итальянский скульптор, живописец, архитектор и поэт эпохи Возрождения',
    era: 'Renaissance',
    category: 'Artist',
    country: 'Italy',
    birthYear: 1475,
    deathYear: 1564,
  },
  {
    name: 'Чингисхан',
    nameEn: 'Genghis Khan',
    description: 'Основатель и первый великий хан Монгольской империи',
    era: 'Medieval',
    category: 'Politician',
    country: 'Mongolia',
    birthYear: 1162,
    deathYear: 1227,
  },
  {
    name: 'Елизавета I',
    nameEn: 'Elizabeth I',
    description: 'Королева Англии и Ирландии, последняя из династии Тюдоров',
    era: '16th Century',
    category: 'Politician',
    country: 'England',
    birthYear: 1533,
    deathYear: 1603,
  },
  {
    name: 'Людвиг ван Бетховен',
    nameEn: 'Ludwig van Beethoven',
    description: 'Немецкий композитор и пианист, ключевая фигура западной классической музыки',
    era: '19th Century',
    category: 'Artist',
    country: 'Germany',
    birthYear: 1770,
    deathYear: 1827,
  },
  {
    name: 'Галилео Галилей',
    nameEn: 'Galileo Galilei',
    description: 'Итальянский физик, астроном и математик, один из основателей современной науки',
    era: '17th Century',
    category: 'Scientist',
    country: 'Italy',
    birthYear: 1564,
    deathYear: 1642,
  },
  {
    name: 'Сократ',
    nameEn: 'Socrates',
    description: 'Древнегреческий философ, один из основателей западной философии',
    era: 'Ancient',
    category: 'Philosopher',
    country: 'Greece',
    birthYear: 470,
    deathYear: 399,
  },
  {
    name: 'Платон',
    nameEn: 'Plato',
    description: 'Древнегреческий философ, ученик Сократа, основатель Академии',
    era: 'Ancient',
    category: 'Philosopher',
    country: 'Greece',
    birthYear: 428,
    deathYear: 348,
  },
  {
    name: 'Аристотель',
    nameEn: 'Aristotle',
    description: 'Древнегреческий философ и ученый, ученик Платона, учитель Александра Македонского',
    era: 'Ancient',
    category: 'Philosopher',
    country: 'Greece',
    birthYear: 384,
    deathYear: 322,
  },
  {
    name: 'Конфуций',
    nameEn: 'Confucius',
    description: 'Древнекитайский философ и мыслитель, основатель конфуцианства',
    era: 'Ancient',
    category: 'Philosopher',
    country: 'China',
    birthYear: 551,
    deathYear: 479,
  },
  {
    name: 'Будда',
    nameEn: 'Buddha',
    description: 'Основатель буддизма, духовный учитель',
    era: 'Ancient',
    category: 'Philosopher',
    country: 'India',
    birthYear: 563,
    deathYear: 483,
  },
  {
    name: 'Иисус Христос',
    nameEn: 'Jesus Christ',
    description: 'Центральная фигура христианства, основатель христианской религии',
    era: 'Ancient',
    category: 'Philosopher',
    country: 'Israel',
    birthYear: 4,
    deathYear: 30,
  },
  {
    name: 'Карл Великий',
    nameEn: 'Charlemagne',
    description: 'Король франков, император Запада, объединитель Европы',
    era: 'Medieval',
    category: 'Politician',
    country: 'France',
    birthYear: 742,
    deathYear: 814,
  },
  {
    name: 'Ричард Львиное Сердце',
    nameEn: 'Richard the Lionheart',
    description: 'Король Англии, участник Третьего крестового похода',
    era: 'Medieval',
    category: 'Military',
    country: 'England',
    birthYear: 1157,
    deathYear: 1199,
  },
  {
    name: 'Саладин',
    nameEn: 'Saladin',
    description: 'Первый султан Египта и Сирии, победитель крестоносцев',
    era: 'Medieval',
    category: 'Military',
    country: 'Egypt',
    birthYear: 1137,
    deathYear: 1193,
  },
  {
    name: 'Данте Алигьери',
    nameEn: 'Dante Alighieri',
    description: 'Итальянский поэт, автор "Божественной комедии"',
    era: 'Medieval',
    category: 'Artist',
    country: 'Italy',
    birthYear: 1265,
    deathYear: 1321,
  },
  {
    name: 'Рафаэль',
    nameEn: 'Raphael',
    description: 'Итальянский живописец и архитектор эпохи Высокого Возрождения',
    era: 'Renaissance',
    category: 'Artist',
    country: 'Italy',
    birthYear: 1483,
    deathYear: 1520,
  },
  {
    name: 'Тициан',
    nameEn: 'Titian',
    description: 'Итальянский живописец эпохи Возрождения, крупнейший представитель венецианской школы',
    era: 'Renaissance',
    category: 'Artist',
    country: 'Italy',
    birthYear: 1488,
    deathYear: 1576,
  },
  {
    name: 'Рафаэль Санти',
    nameEn: 'Raphael',
    description: 'Итальянский живописец и архитектор эпохи Возрождения',
    era: 'Renaissance',
    category: 'Artist',
    country: 'Italy',
    birthYear: 1483,
    deathYear: 1520,
  },
  {
    name: 'Николай Коперник',
    nameEn: 'Nicolaus Copernicus',
    description: 'Польский астроном, создатель гелиоцентрической системы мира',
    era: 'Renaissance',
    category: 'Scientist',
    country: 'Poland',
    birthYear: 1473,
    deathYear: 1543,
  },
  {
    name: 'Генрих VIII',
    nameEn: 'Henry VIII',
    description: 'Король Англии, основатель англиканской церкви',
    era: '16th Century',
    category: 'Politician',
    country: 'England',
    birthYear: 1491,
    deathYear: 1547,
  },
  {
    name: 'Елизавета I',
    nameEn: 'Elizabeth I',
    description: 'Королева Англии, "Золотой век" английской истории',
    era: '16th Century',
    category: 'Politician',
    country: 'England',
    birthYear: 1533,
    deathYear: 1603,
  },
  {
    name: 'Иван Грозный',
    nameEn: 'Ivan the Terrible',
    description: 'Первый русский царь, создатель централизованного государства',
    era: '16th Century',
    category: 'Politician',
    country: 'Russia',
    birthYear: 1530,
    deathYear: 1584,
  },
  {
    name: 'Петр I',
    nameEn: 'Peter the Great',
    description: 'Русский император, реформатор, основатель Санкт-Петербурга',
    era: '17th Century',
    category: 'Politician',
    country: 'Russia',
    birthYear: 1672,
    deathYear: 1725,
  },
  {
    name: 'Екатерина II',
    nameEn: 'Catherine the Great',
    description: 'Русская императрица, эпоха просвещенного абсолютизма',
    era: '18th Century',
    category: 'Politician',
    country: 'Russia',
    birthYear: 1729,
    deathYear: 1796,
  },
  {
    name: 'Людовик XIV',
    nameEn: 'Louis XIV',
    description: 'Король Франции, "Король-Солнце", самый долгий правящий монарх в истории',
    era: '17th Century',
    category: 'Politician',
    country: 'France',
    birthYear: 1638,
    deathYear: 1715,
  },
  {
    name: 'Вольтер',
    nameEn: 'Voltaire',
    description: 'Французский философ, писатель, один из основоположников Просвещения',
    era: '18th Century',
    category: 'Philosopher',
    country: 'France',
    birthYear: 1694,
    deathYear: 1778,
  },
  {
    name: 'Жан-Жак Руссо',
    nameEn: 'Jean-Jacques Rousseau',
    description: 'Французский философ, писатель, мыслитель эпохи Просвещения',
    era: '18th Century',
    category: 'Philosopher',
    country: 'France',
    birthYear: 1712,
    deathYear: 1778,
  },
  {
    name: 'Иоганн Себастьян Бах',
    nameEn: 'Johann Sebastian Bach',
    description: 'Немецкий композитор, органист, один из величайших композиторов в истории',
    era: '18th Century',
    category: 'Artist',
    country: 'Germany',
    birthYear: 1685,
    deathYear: 1750,
  },
  {
    name: 'Франц Иосиф Гайдн',
    nameEn: 'Franz Joseph Haydn',
    description: 'Австрийский композитор, один из основоположников венской классической школы',
    era: '18th Century',
    category: 'Artist',
    country: 'Austria',
    birthYear: 1732,
    deathYear: 1809,
  },
  {
    name: 'Джордж Вашингтон',
    nameEn: 'George Washington',
    description: 'Первый президент США, один из отцов-основателей',
    era: '18th Century',
    category: 'Politician',
    country: 'United States',
    birthYear: 1732,
    deathYear: 1799,
  },
  {
    name: 'Томас Джефферсон',
    nameEn: 'Thomas Jefferson',
    description: 'Третий президент США, автор Декларации независимости',
    era: '18th Century',
    category: 'Politician',
    country: 'United States',
    birthYear: 1743,
    deathYear: 1826,
  },
  {
    name: 'Авраам Линкольн',
    nameEn: 'Abraham Lincoln',
    description: '16-й президент США, освободитель рабов',
    era: '19th Century',
    category: 'Politician',
    country: 'United States',
    birthYear: 1809,
    deathYear: 1865,
  },
  {
    name: 'Отто фон Бисмарк',
    nameEn: 'Otto von Bismarck',
    description: 'Канцлер Германии, объединитель немецких земель',
    era: '19th Century',
    category: 'Politician',
    country: 'Germany',
    birthYear: 1815,
    deathYear: 1898,
  },
  {
    name: 'Виктор Гюго',
    nameEn: 'Victor Hugo',
    description: 'Французский писатель, поэт, автор "Отверженных" и "Собора Парижской Богоматери"',
    era: '19th Century',
    category: 'Artist',
    country: 'France',
    birthYear: 1802,
    deathYear: 1885,
  },
  {
    name: 'Чарльз Дарвин',
    nameEn: 'Charles Darwin',
    description: 'Английский натуралист, создатель теории эволюции',
    era: '19th Century',
    category: 'Scientist',
    country: 'England',
    birthYear: 1809,
    deathYear: 1882,
  },
  {
    name: 'Мария Кюри',
    nameEn: 'Marie Curie',
    description: 'Польско-французский физик и химик, первая женщина-лауреат Нобелевской премии',
    era: '20th Century',
    category: 'Scientist',
    country: 'Poland',
    birthYear: 1867,
    deathYear: 1934,
  },
  {
    name: 'Никола Тесла',
    nameEn: 'Nikola Tesla',
    description: 'Сербско-американский изобретатель, инженер, пионер электротехники',
    era: '20th Century',
    category: 'Scientist',
    country: 'Serbia',
    birthYear: 1856,
    deathYear: 1943,
  },
  {
    name: 'Уинстон Черчилль',
    nameEn: 'Winston Churchill',
    description: 'Премьер-министр Великобритании во время Второй мировой войны',
    era: '20th Century',
    category: 'Politician',
    country: 'England',
    birthYear: 1874,
    deathYear: 1965,
  },
  {
    name: 'Франклин Рузвельт',
    nameEn: 'Franklin D. Roosevelt',
    description: '32-й президент США, лидер во время Великой депрессии и Второй мировой войны',
    era: '20th Century',
    category: 'Politician',
    country: 'United States',
    birthYear: 1882,
    deathYear: 1945,
  },
  {
    name: 'Адольф Гитлер',
    nameEn: 'Adolf Hitler',
    description: 'Лидер нацистской Германии, инициатор Второй мировой войны',
    era: '20th Century',
    category: 'Politician',
    country: 'Germany',
    birthYear: 1889,
    deathYear: 1945,
  },
  {
    name: 'Иосиф Сталин',
    nameEn: 'Joseph Stalin',
    description: 'Советский государственный деятель, генералиссимус',
    era: '20th Century',
    category: 'Politician',
    country: 'Russia',
    birthYear: 1878,
    deathYear: 1953,
  },
  {
    name: 'Мартин Лютер Кинг',
    nameEn: 'Martin Luther King Jr.',
    description: 'Американский баптистский проповедник, лидер движения за гражданские права',
    era: '20th Century',
    category: 'Politician',
    country: 'United States',
    birthYear: 1929,
    deathYear: 1968,
  },
  {
    name: 'Нельсон Мандела',
    nameEn: 'Nelson Mandela',
    description: 'Президент ЮАР, борец против апартеида, лауреат Нобелевской премии мира',
    era: '20th Century',
    category: 'Politician',
    country: 'South Africa',
    birthYear: 1918,
    deathYear: 2013,
  },
  {
    name: 'Пабло Пикассо',
    nameEn: 'Pablo Picasso',
    description: 'Испанский художник, скульптор, один из основоположников кубизма',
    era: '20th Century',
    category: 'Artist',
    country: 'Spain',
    birthYear: 1881,
    deathYear: 1973,
  },
  {
    name: 'Винсент ван Гог',
    nameEn: 'Vincent van Gogh',
    description: 'Голландский художник-постимпрессионист, один из самых известных художников',
    era: '19th Century',
    category: 'Artist',
    country: 'Netherlands',
    birthYear: 1853,
    deathYear: 1890,
  },
  {
    name: 'Клод Моне',
    nameEn: 'Claude Monet',
    description: 'Французский художник, основатель импрессионизма',
    era: '19th Century',
    category: 'Artist',
    country: 'France',
    birthYear: 1840,
    deathYear: 1926,
  },
  {
    name: 'Фридрих Ницше',
    nameEn: 'Friedrich Nietzsche',
    description: 'Немецкий философ, культуролог, поэт',
    era: '19th Century',
    category: 'Philosopher',
    country: 'Germany',
    birthYear: 1844,
    deathYear: 1900,
  },
  {
    name: 'Зигмунд Фрейд',
    nameEn: 'Sigmund Freud',
    description: 'Австрийский психолог, психиатр, основатель психоанализа',
    era: '20th Century',
    category: 'Scientist',
    country: 'Austria',
    birthYear: 1856,
    deathYear: 1939,
  },
  {
    name: 'Лев Толстой',
    nameEn: 'Leo Tolstoy',
    description: 'Русский писатель, мыслитель, автор "Войны и мира"',
    era: '19th Century',
    category: 'Artist',
    country: 'Russia',
    birthYear: 1828,
    deathYear: 1910,
  },
  {
    name: 'Федор Достоевский',
    nameEn: 'Fyodor Dostoevsky',
    description: 'Русский писатель, философ, автор "Преступления и наказания"',
    era: '19th Century',
    category: 'Artist',
    country: 'Russia',
    birthYear: 1821,
    deathYear: 1881,
  },
  {
    name: 'Антон Чехов',
    nameEn: 'Anton Chekhov',
    description: 'Русский писатель, драматург, мастер короткого рассказа',
    era: '19th Century',
    category: 'Artist',
    country: 'Russia',
    birthYear: 1860,
    deathYear: 1904,
  },
  {
    name: 'Александр Пушкин',
    nameEn: 'Alexander Pushkin',
    description: 'Русский поэт, драматург, прозаик, основоположник современной русской литературы',
    era: '19th Century',
    category: 'Artist',
    country: 'Russia',
    birthYear: 1799,
    deathYear: 1837,
  },
  {
    name: 'Иоганн Вольфганг фон Гёте',
    nameEn: 'Johann Wolfgang von Goethe',
    description: 'Немецкий поэт, писатель, мыслитель, автор "Фауста"',
    era: '18th Century',
    category: 'Artist',
    country: 'Germany',
    birthYear: 1749,
    deathYear: 1832,
  },
  {
    name: 'Джордж Байрон',
    nameEn: 'Lord Byron',
    description: 'Английский поэт-романтик, один из величайших поэтов',
    era: '19th Century',
    category: 'Artist',
    country: 'England',
    birthYear: 1788,
    deathYear: 1824,
  },
  {
    name: 'Оскар Уайльд',
    nameEn: 'Oscar Wilde',
    description: 'Ирландский писатель, поэт, драматург, автор "Портрета Дориана Грея"',
    era: '19th Century',
    category: 'Artist',
    country: 'Ireland',
    birthYear: 1854,
    deathYear: 1900,
  },
  {
    name: 'Эрнест Хемингуэй',
    nameEn: 'Ernest Hemingway',
    description: 'Американский писатель, журналист, лауреат Нобелевской премии по литературе',
    era: '20th Century',
    category: 'Artist',
    country: 'United States',
    birthYear: 1899,
    deathYear: 1961,
  },
  {
    name: 'Марк Твен',
    nameEn: 'Mark Twain',
    description: 'Американский писатель, журналист, автор "Приключений Тома Сойера"',
    era: '19th Century',
    category: 'Artist',
    country: 'United States',
    birthYear: 1835,
    deathYear: 1910,
  },
  {
    name: 'Джордж Бернард Шоу',
    nameEn: 'George Bernard Shaw',
    description: 'Ирландский драматург, лауреат Нобелевской премии по литературе',
    era: '20th Century',
    category: 'Artist',
    country: 'Ireland',
    birthYear: 1856,
    deathYear: 1950,
  },
  {
    name: 'Франц Шуберт',
    nameEn: 'Franz Schubert',
    description: 'Австрийский композитор, один из основоположников романтизма в музыке',
    era: '19th Century',
    category: 'Artist',
    country: 'Austria',
    birthYear: 1797,
    deathYear: 1828,
  },
  {
    name: 'Фредерик Шопен',
    nameEn: 'Frédéric Chopin',
    description: 'Польский композитор и пианист, один из величайших композиторов-романтиков',
    era: '19th Century',
    category: 'Artist',
    country: 'Poland',
    birthYear: 1810,
    deathYear: 1849,
  },
  {
    name: 'Петр Чайковский',
    nameEn: 'Pyotr Tchaikovsky',
    description: 'Русский композитор, один из величайших композиторов в истории музыки',
    era: '19th Century',
    category: 'Artist',
    country: 'Russia',
    birthYear: 1840,
    deathYear: 1893,
  },
  {
    name: 'Иоганн Штраус',
    nameEn: 'Johann Strauss II',
    description: 'Австрийский композитор, "король вальса"',
    era: '19th Century',
    category: 'Artist',
    country: 'Austria',
    birthYear: 1825,
    deathYear: 1899,
  },
  {
    name: 'Рихард Вагнер',
    nameEn: 'Richard Wagner',
    description: 'Немецкий композитор, дирижер, реформатор оперы',
    era: '19th Century',
    category: 'Artist',
    country: 'Germany',
    birthYear: 1813,
    deathYear: 1883,
  },
  {
    name: 'Джузеппе Верди',
    nameEn: 'Giuseppe Verdi',
    description: 'Итальянский композитор, один из величайших оперных композиторов',
    era: '19th Century',
    category: 'Artist',
    country: 'Italy',
    birthYear: 1813,
    deathYear: 1901,
  },
  {
    name: 'Сунь Ятсен',
    nameEn: 'Sun Yat-sen',
    description: 'Китайский революционер, основатель Китайской Республики',
    era: '20th Century',
    category: 'Politician',
    country: 'China',
    birthYear: 1866,
    deathYear: 1925,
  },
  {
    name: 'Махатма Ганди',
    nameEn: 'Mahatma Gandhi',
    description: 'Индийский политический деятель, лидер движения за независимость Индии',
    era: '20th Century',
    category: 'Politician',
    country: 'India',
    birthYear: 1869,
    deathYear: 1948,
  },
  {
    name: 'Мао Цзэдун',
    nameEn: 'Mao Zedong',
    description: 'Китайский революционер, основатель КНР',
    era: '20th Century',
    category: 'Politician',
    country: 'China',
    birthYear: 1893,
    deathYear: 1976,
  },
  {
    name: 'Владимир Ленин',
    nameEn: 'Vladimir Lenin',
    description: 'Русский революционер, основатель Советского государства',
    era: '20th Century',
    category: 'Politician',
    country: 'Russia',
    birthYear: 1870,
    deathYear: 1924,
  },
  {
    name: 'Стив Джобс',
    nameEn: 'Steve Jobs',
    description: 'Американский предприниматель, сооснователь Apple Inc.',
    era: '20th Century',
    category: 'Other',
    country: 'United States',
    birthYear: 1955,
    deathYear: 2011,
  },
  {
    name: 'Билл Гейтс',
    nameEn: 'Bill Gates',
    description: 'Американский предприниматель, сооснователь Microsoft',
    era: '20th Century',
    category: 'Other',
    country: 'United States',
    birthYear: 1955,
    deathYear: null,
  },
];

async function main() {
  console.log('Seeding database...');

  await prisma.historicalPerson.createMany({
    data: historicalPersons,
    skipDuplicates: true,
  });

  console.log('Seeding completed!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
